In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D

# Plot figure
fig = plt.figure()
ax = plt.subplot(111)
ax.plot(1,1)

In [ ]:
from greedy_solver import GreedySolver 

game_info= {
  "mapName": "EL 1",
  "vehicle": {
    "length": 200,
    "width": 120,
    "height": 180
  },
  "dimensions": [
    {
      "id": 0,
      "width": 35,
      "length": 50,
      "height": 28,
      "weightClass": 2,
      "orderClass": 1
    },{
      "id": 1,
      "width": 15,
      "length": 25,
      "height": 10,
      "weightClass": 1,
      "orderClass": 1
    }
  ]
}

try: 
    solution.clear()
except:
    pass

greedy = GreedySolver(game_info)
solution = greedy.Solve()	

print(len(solution))
for s in solution:
    print(s, end = '\n\n')

In [ ]:
print(solution)

In [ ]:
p={'id': 39, 'x1': 147, 'x2': 147, 'x3': 147, 'x4': 147, 'x5': 185, 'x6': 185, 'x7': 185, 'x8': 185, 'y1': 100, 'y2': 100, 'y3': 100, 'y4': 100, 'y5': 122, 'y6': 122, 'y7': 122, 'y8': 122, 'z1': 37, 'z2': 37, 'z3': 37, 'z4': 37, 'z5': 52, 'z6': 52, 'z7': 52, 'z8': 52, 'weightClass': 2, 'orderClass': 2}
print(p['x5']-p['x1'], p['y5']-p['y1'], p['z5']-p['z1'])

In [5]:
import numpy as np

a = np.ones((10,8,5), np.int8)

#a[10,8,5] = 5.1


a[0:9, 0:5, 0] = 0

print(a)


[[[0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [0 1 1 1 1]
  [1 1 1 1 1]
  [1

In [ ]:
print(type(2))

In [ ]:
from itertools import permutations

for combo in permutations([0, 1, 2], 3):  # 2 for pairs, 3 for triplets, etc
    print(combo)

In [2]:
from itertools import islice

lista = iter(['a', 'b', 'c', 'd', 'e', 'f', 'g'])

for l in lista:
    
    if l == 'c':
        next(islice(lista, 3, 3), None)    
    print (l)



a
b
c
g


In [4]:
import timeit

start = timeit.default_timer()

for i in range(10000):
    pass

medel = timeit.default_timer()

for i in range(10000):
    pass

stop = timeit.default_timer()

print(start, medel, stop)

8996.7125561 8996.7129726 8996.713354


In [9]:
import numpy as np

set(np.array(3, 5))

TypeError: Cannot interpret '5' as a data type